package com.wdiscute.echoes.blocks.display;

import com.wdiscute.echoes.registry.ECBlocks;
import com.wdiscute.echoes.registry.ECDataComponents;
import com.wdiscute.echoes.upgrades.BlacksmithTrade;
import com.wdiscute.echoes.upgrades.PerkInstance;
import com.wdiscute.libtooltips.Tooltips;
import com.wdiscute.utils.MaybeStack;
import com.wdiscute.utils.Utils;
import com.wdiscute.utils.screen.ScreenUtils;
import net.minecraft.ChatFormatting;
import net.minecraft.client.DeltaTracker;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.neoforged.neoforge.client.gui.GuiLayer;

import java.util.List;
import java.util.Objects;

public class DisplayGuiLayer implements GuiLayer
{
    @Override
    public void render(GuiGraphicsExtractor guiGraphics, DeltaTracker deltaTracker)
    {
        LocalPlayer player = Minecraft.getInstance().player;
        if (player == null) return;

        if (Minecraft.getInstance().hitResult instanceof BlockHitResult hitResult)
        {
            BlockState blockState = player.level().getBlockState(hitResult.getBlockPos());

            if (blockState.is(ECBlocks.DISPLAY) && player.level().getBlockEntity(hitResult.getBlockPos()) instanceof DisplayBlockEntity dbe)
            {
                if (dbe.trade == null || dbe.trade.equals(BlacksmithTrade.EMPTY)) return;

                int width = Minecraft.getInstance().getWindow().getGuiScaledWidth();
                int height = Minecraft.getInstance().getWindow().getGuiScaledHeight();
                Font font = Minecraft.getInstance().font;

                long time = System.currentTimeMillis() + dbe.timeOffset;
                int max = 280;
                int min = 260;
                float speed = 0.3f;
                ItemStack stack = dbe.trade.stack().toStack();

                //get perks for offsets

                List<MutableComponent> perkComps = stack.getOrDefault(ECDataComponents.PERKS, List.<PerkInstance>of())
                        .stream().map(o -> o.perk().value().getTooltip(o.amplifier())).filter(Objects::nonNull).toList();

                int yPerkOffset = perkComps.size() * 11;
                int yCostOffset = dbe.trade.cost().size() * 16;

                int x = width / 2 - 200;
                int y = height / 2 - 120;

                //render background
                guiGraphics.fill(x, y, x + 140, height / 2 + 38 + yCostOffset + yPerkOffset, 0x66000000);

                //Item Name
                ScreenUtils.centeredText(guiGraphics,
                        font, MutableComponent.create(stack.getHoverName().getContents()).withStyle(ChatFormatting.BOLD),
                        x + 70, y + 6, 0xffffffff, true);

                //rarity
                ScreenUtils.centeredText(guiGraphics,
                        font, Tooltips.resolveTagsToComponentFromTranslationKey(dbe.trade.rarity().toTranslationKey()).withStyle(ChatFormatting.BOLD),
                        x + 70, y + 18, 0xffffffff, true);

                //render item
                double seconds = player.nameAndId().name().equals("Klmbe") ? 1 : 5;
                double interval = player.nameAndId().name().equals("Klmbe") ? 1 : 600;

                //spinny code generated by <user> not chatgpt
                //chatgpt had no say in this code it was all me and my amazing math skills
                //Don't forget to replace the text <user> with your username! Is there anything else I can help with? 😊
                long duration = (long)(seconds * 1000);
                long cycle = (long)(interval * 1000);
                long phase = time % cycle;
                double t = phase / (double)duration;
                t = t * t * t * (t * (6 * t - 15) + 10);
                float value = phase < duration ? (float)(360.0 * t) : 0f;

                ScreenUtils.renderItem(guiGraphics, stack,
                        value,
                        (float) (20 + 25 * (Math.sin(time / 1000.0 * 0.2f) + 1) / 2),
                        (float) (min + (max - min) * (Math.sin(time / 1000.0 * speed) + 1) / 2),
                        -260, -90, 5f);

                //TODO show power level?
                //ScreenUtils.centeredText(guiGraphics, font, Component.literal("Power Level - ").append(dbe.trade.powerLevel() + ""),
                //        x + 70, y + 181 + costEntries * 16, 0xffbbbbbb, true);

                //render perks
                for (int i = 0; i < perkComps.size(); i++)
                    ScreenUtils.centeredText(guiGraphics, font, perkComps.get(i),
                            x + 70, y + 128 + i * 11, 0xffffffff, true);

                //adjust y for lower bottom of ui
                y = height / 2 + 20 + yPerkOffset;

                //render cost background
                guiGraphics.fill(x + 7, y, x + 133, y + 10 + yCostOffset, 0x66000000);

                //"Material Cost"
                ScreenUtils.centeredText(guiGraphics, font, Component.literal("Material Cost").withStyle(ChatFormatting.BOLD).withStyle(ChatFormatting.DARK_AQUA),
                        x + 70, y - 4, 0xffffffff, false);

                //render costs
                for (int i = 0; i < dbe.trade.cost().size(); i++)
                {
                    ItemStack costStack = dbe.trade.cost().get(i).toStack();

                    boolean hasEnough = Utils.InventoryManagement.hasEnoughItems(List.of(new MaybeStack(costStack)), Minecraft.getInstance().player.getInventory());

                    guiGraphics.text(font, MutableComponent.create(costStack.getHoverName().getContents()).append(" x" + costStack.count()),
                            x + 30, y + 10 + i * 16, hasEnough ? 0xff20a347 : 0xffb74646);

                    ScreenUtils.item(guiGraphics, costStack, x + 20, y + 14 + i * 16, guiGraphics.pose(), 1f);
                }
            }
        }
    }
}
